=== jbrmmg/Monitor/src/main/xsd/monitor-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jbr="http://jbrmmg.me.uk/MonitorConfig"
            targetNamespace="http://jbrmmg.me.uk/MonitorConfig"
            elementFormDefault="qualified">

    <xsd:simpleType name="IPv4Address">
        <xsd:annotation>
            <xsd:documentation>IPv4 address in dot-decimal notation. Equivalent to [0-255].[0-255].[0-255].[0-255]</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="((1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType  name="MacAddress">
        <xsd:annotation>
            <xsd:documentation>Mac Address</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction  base="xsd:string">
            <xsd:pattern  value="[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="PortNumber">
        <xsd:annotation>
            <xsd:documentation>Port Number, digits</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([0-9])+" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="DNSType">
        <xsd:attribute name="name" type="xsd:string"  use="required"/>
    </xsd:complexType>

    <xsd:complexType name="DNSsType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="DNS" type="jbr:DNSType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="MonitoredItemType">
        <xsd:attribute name="host" type="xsd:string" default="localhost"/>
        <xsd:attribute name="port" type="jbr:PortNumber" use="required"/>
        <xsd:attribute name="name" type="xsd:string" default=""/>
    </xsd:complexType>

    <xsd:complexType name="MonitoredItemsType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="MonitoredItem" type="jbr:MonitoredItemType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="MonitorType">
        <xsd:sequence>
            <xsd:element name="MonitoredItems" type="jbr:MonitoredItemsType"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="port" type="jbr:PortNumber" use="required"/>
        <xsd:attribute name="primary" default="no">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="yes" />
                    <xsd:enumeration value="no" />
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="MonitorsType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="Monitor" type="jbr:MonitorType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="MachineType">
        <xsd:sequence>
            <xsd:element name="DNSs" type="jbr:DNSsType"/>
            <xsd:element name="Monitors" type="jbr:MonitorsType"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="jbr:MacAddress" use="required"/>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="ip" type="jbr:IPv4Address" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="MachinesType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="Machine" type="jbr:MachineType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="Machines" type="jbr:MachinesType"/>
</xsd:schema>

=== jbrmmg/Monitor/src/main/resources/MonitorConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<Machines xmlns="http://jbrmmg.me.uk/MonitorConfig"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://jbrmmg.me.uk/MonitorConfig file://../xsd/monitor-config.xsd">
    <Machine id="74:D4:35:1F:22:07" name="Triggers Broom" ip="192.168.1.64">
        <DNSs>
            <DNS name="triggersbroom.jbrmmg.me.uk"/>
            <DNS name="mysql.jbrmmg.me.uk"/>
        </DNSs>
        <Monitors>
            <Monitor name="Triggers Broom Monitor (Debug)" port="13021" primary="yes">
                <MonitoredItems>
                    <MonitoredItem port="10001" name="Test Check"/>
                    <MonitoredItem port="10009"/>
                    <MonitoredItem port="10013"/>
                    <MonitoredItem port="10017"/>
                    <MonitoredItem host="192.168.1.64"  port="10021" name="Dev monitor"/>
                </MonitoredItems>
            </Monitor>
            <Monitor name="Triggers Broom Monitor (Dev)" port="10021">
                <MonitoredItems>
                    <MonitoredItem port="10001"/>
                    <MonitoredItem port="10009"/>
                    <MonitoredItem port="10013"/>
                    <MonitoredItem port="10017"/>
                </MonitoredItems>
            </Monitor>
            <Monitor name="Triggers Broom Monitor" port="12021" primary="yes">
                <MonitoredItems>
                    <MonitoredItem port="12001"/>
                    <MonitoredItem port="12009"/>
                    <MonitoredItem port="12013"/>
                    <MonitoredItem port="12017"/>
                    <MonitoredItem host="192.168.1.65"  port="12021" name="Small Broom Monitor"/>
                    <MonitoredItem host="192.168.1.66"  port="12021" name="Medium Broom Monitor"/>
                    <MonitoredItem host="192.168.1.203" port="12021" name="Raspberry Pi Monitor"/>
                    <MonitoredItem host="192.168.1.204" port="12021" name="Raspberry Pi 2 Monitor"/>
                    <MonitoredItem host="192.168.1.205" port="12021" name="Raspberry Pi 3 Monitor"/>
                    <MonitoredItem host="192.168.1.202" port="12021" name="Raspberry Pi 4 Monitor"/>
                    <MonitoredItem port="10001"/>
                    <MonitoredItem port="10009"/>
                    <MonitoredItem port="10013"/>
                    <MonitoredItem port="10017"/>
                </MonitoredItems>
            </Monitor>
        </Monitors>
    </Machine>
    <Machine id="80:A5:89:6A:D1:37" name="Tiny Broom" ip="192.168.1.70">
        <DNSs>
            <DNS name="tinybroom.jbrmmg.me.uk"/>
        </DNSs>
        <Monitors>
            <Monitor name="Tiny Broom" port="12021" primary="yes">
                <MonitoredItems>
                    <MonitoredItem host="192.168.1.64"  port="12021" name="Triggers Broom Monitor"/>
                    <MonitoredItem host="192.168.1.66"  port="12021" name="Medium Broom Monitor"/>
                    <MonitoredItem host="192.168.1.203" port="12021" name="Raspberry Pi Monitor"/>
                    <MonitoredItem host="192.168.1.204" port="12021" name="Raspberry Pi 2 Monitor"/>
                    <MonitoredItem host="192.168.1.205" port="12021" name="Raspberry Pi 3 Monitor"/>
                    <MonitoredItem host="192.168.1.202" port="12021" name="Raspberry Pi 4 Monitor"/>
                </MonitoredItems>
            </Monitor>
        </Monitors>
    </Machine>
    <Machine id="40:8D:5C:A6:79:90" name="Small Broom" ip="192.168.1.65">
        <DNSs>
            <DNS name="smallbroom.jbrmmg.me.uk"/>
        </DNSs>
        <Monitors>
            <Monitor name="Small Broom" port="12021" primary="yes">
                <MonitoredItems>
                    <MonitoredItem host="192.168.1.64"  port="12021" name="Triggers Broom Monitor"/>
                    <MonitoredItem host="192.168.1.66"  port="12021" name="Medium Broom Monitor"/>
                    <MonitoredItem host="192.168.1.203" port="12021" name="Raspberry Pi Monitor"/>
                    <MonitoredItem host="192.168.1.204" port="12021" name="Raspberry Pi 2 Monitor"/>
                    <MonitoredItem host="192.168.1.205" port="12021" name="Raspberry Pi 3 Monitor"/>
                    <MonitoredItem host="192.168.1.202" port="12021" name="Raspberry Pi 4 Monitor"/>
                </MonitoredItems>
            </Monitor>
        </Monitors>
    </Machine>
    <Machine id="E0:D5:5E:18:51:76" name="Medium Broom" ip="192.168.1.66">
        <DNSs>
            <DNS name="mediumbroom.jbrmmg.me.uk"/>
        </DNSs>
        <Monitors>
            <Monitor name="Medium Broom" port="12021" primary="yes">
                <MonitoredItems>
                    <MonitoredItem host="192.168.1.64"  port="12021" name="Triggers Broom Monitor"/>
                    <MonitoredItem host="192.168.1.65"  port="12021" name="Small Broom Monitor"/>
                    <MonitoredItem host="192.168.1.203" port="12021" name="Raspberry Pi Monitor"/>
                    <MonitoredItem host="192.168.1.204" port="12021" name="Raspberry Pi 2 Monitor"/>
                    <MonitoredItem host="192.168.1.205" port="12021" name="Raspberry Pi 3 Monitor"/>
                    <MonitoredItem host="192.168.1.202" port="12021" name="Raspberry Pi 4 Monitor"/>
                </MonitoredItems>
            </Monitor>
        </Monitors>
    </Machine>
    <Machine id="B8:27:EB:76:7B:E5" name="Raspbian Pi" ip="192.168.1.203">
        <DNSs>
            <DNS name="raspbianpi.jbrmmg.me.uk"/>
        </DNSs>
        <Monitors>
            <Monitor name="Raspberry Pi" port="12021" primary="yes">
                <MonitoredItems>
                    <MonitoredItem host="192.168.1.64"  port="12021" name="Triggers Broom Monitor"/>
                    <MonitoredItem host="192.168.1.65"  port="12021" name="Small Broom Monitor"/>
                    <MonitoredItem host="192.168.1.66"  port="12021" name="Medium Broom Monitor"/>
                    <MonitoredItem host="192.168.1.204" port="12021" name="Raspberry Pi 2 Monitor"/>
                    <MonitoredItem host="192.168.1.205" port="12021" name="Raspberry Pi 3 Monitor"/>
                    <MonitoredItem host="192.168.1.202" port="12021" name="Raspberry Pi 4 Monitor"/>
                </MonitoredItems>
            </Monitor>
        </Monitors>
    </Machine>
    <Machine id="B8:27:EB:93:38:91" name="Raspbian Pi 2" ip="192.168.1.204">
        <DNSs>
            <DNS name="raspbianpi2.jbrmmg.me.uk"/>
        </DNSs>
        <Monitors>
            <Monitor name="Raspberry Pi 2" port="12021" primary="yes">
                <MonitoredItems>
                    <MonitoredItem host="192.168.1.64"  port="12021" name="Triggers Broom Monitor"/>
                    <MonitoredItem host="192.168.1.65"  port="12021" name="Small Broom Monitor"/>
                    <MonitoredItem host="192.168.1.66"  port="12021" name="Medium Broom Monitor"/>
                    <MonitoredItem host="192.168.1.203" port="12021" name="Raspberry Pi Monitor"/>
                    <MonitoredItem host="192.168.1.205" port="12021" name="Raspberry Pi 3 Monitor"/>
                    <MonitoredItem host="192.168.1.202" port="12021" name="Raspberry Pi 4 Monitor"/>
                </MonitoredItems>
            </Monitor>
        </Monitors>
    </Machine>
    <Machine id="B8:27:EB:BC:05:67" name="Raspbian Pi 3" ip="192.168.1.205">
        <DNSs>
            <DNS name="raspbianpi3.jbrmmg.me.uk"/>
        </DNSs>
        <Monitors>
            <Monitor name="Raspberry Pi 3" port="12021" primary="yes">
                <MonitoredItems>
                    <MonitoredItem host="192.168.1.64"  port="12021" name="Triggers Broom Monitor"/>
                    <MonitoredItem host="192.168.1.65"  port="12021" name="Small Broom Monitor"/>
                    <MonitoredItem host="192.168.1.66"  port="12021" name="Medium Broom Monitor"/>
                    <MonitoredItem host="192.168.1.203" port="12021" name="Raspberry Pi Monitor"/>
                    <MonitoredItem host="192.168.1.204" port="12021" name="Raspberry Pi 2 Monitor"/>
                    <MonitoredItem host="192.168.1.202" port="12021" name="Raspberry Pi 4 Monitor"/>
                </MonitoredItems>
            </Monitor>
        </Monitors>
    </Machine>
    <Machine id="B8:27:EB:B3:6A:C2" name="Raspbian Pi 4" ip="192.168.1.202">
        <DNSs>
            <DNS name="raspbianpi4.jbrmmg.me.uk"/>
        </DNSs>
        <Monitors>
            <Monitor name="Raspberry Pi 4" port="12021" primary="yes">
                <MonitoredItems>
                    <MonitoredItem host="192.168.1.64"  port="12021" name="Triggers Broom Monitor"/>
                    <MonitoredItem host="192.168.1.65"  port="12021" name="Small Broom Monitor"/>
                    <MonitoredItem host="192.168.1.66"  port="12021" name="Medium Broom Monitor"/>
                    <MonitoredItem host="192.168.1.203" port="12021" name="Raspberry Pi Monitor"/>
                    <MonitoredItem host="192.168.1.204" port="12021" name="Raspberry Pi 2 Monitor"/>
                    <MonitoredItem host="192.168.1.205" port="12021" name="Raspberry Pi 3 Monitor"/>
                </MonitoredItems>
            </Monitor>
        </Monitors>
    </Machine>
</Machines>
